config/routes.rb
Rails.application.routes.draw do
  resources :micropsts
  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropst.rb
class Micropst < ApplicationRecord
    belongs_to :user
    validates :content, length: {maximum: 140},
        presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :micropst
    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello
        render html: "Aloha, World!"
    end
end

app/controllers/micropsts_controller.rb
class MicropstsController < ApplicationController
  before_action :set_micropst, only: %i[ show edit update destroy ]

  # GET /micropsts or /micropsts.json
  def index
    @micropsts = Micropst.all
  end

  # GET /micropsts/1 or /micropsts/1.json
  def show
  end

  # GET /micropsts/new
  def new
    @micropst = Micropst.new
  end

  # GET /micropsts/1/edit
  def edit
  end

  # POST /micropsts or /micropsts.json
  def create
    @micropst = Micropst.new(micropst_params)

    respond_to do |format|
      if @micropst.save
        format.html { redirect_to micropst_url(@micropst), notice: "Micropst was successfully created." }
        format.json { render :show, status: :created, location: @micropst }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @micropst.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /micropsts/1 or /micropsts/1.json
  def update
    respond_to do |format|
      if @micropst.update(micropst_params)
        format.html { redirect_to micropst_url(@micropst), notice: "Micropst was successfully updated." }
        format.json { render :show, status: :ok, location: @micropst }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropst.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micropsts/1 or /micropsts/1.json
  def destroy
    @micropst.destroy

    respond_to do |format|
      format.html { redirect_to micropsts_url, notice: "Micropst was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropst
      @micropst = Micropst.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropst_params
      params.require(:micropst).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/micropsts_helper.rb
module MicropstsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/micropsts/_form.html.erb
<%= form_with(model: micropst) do |form| %>
  <% if micropst.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropst.errors.count, "error") %> prohibited this micropst from being saved:</h2>

      <ul>
        <% micropst.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/micropsts/_micropst.html.erb
<div id="<%= dom_id micropst %>">
  <p>
    <strong>Content:</strong>
    <%= micropst.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= micropst.user_id %>
  </p>

</div>

app/views/micropsts/edit.html.erb
<h1>Editing micropst</h1>

<%= render "form", micropst: @micropst %>

<br>

<div>
  <%= link_to "Show this micropst", @micropst %> |
  <%= link_to "Back to micropsts", micropsts_path %>
</div>

app/views/micropsts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Micropsts</h1>

<div id="micropsts">
  <% @micropsts.each do |micropst| %>
    <%= render micropst %>
    <p>
      <%= link_to "Show this micropst", micropst %>
    </p>
  <% end %>
</div>

<%= link_to "New micropst", new_micropst_path %>

app/views/micropsts/new.html.erb
<h1>New micropst</h1>

<%= render "form", micropst: @micropst %>

<br>

<div>
  <%= link_to "Back to micropsts", micropsts_path %>
</div>

app/views/micropsts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @micropst %>

<div>
  <%= link_to "Edit this micropst", edit_micropst_path(@micropst) %> |
  <%= link_to "Back to micropsts", micropsts_path %>

  <%= button_to "Destroy this micropst", @micropst, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>